version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_retro-ps5
    environment:
      - MONGO_INITDB_DATABASE=retro-ps5
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - retro5

  mongo-express:
    image: mongo-express
    container_name: mongo_express_retro-ps5
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb_retro-ps5
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
    networks:
      - retro5

volumes:
  mongodb_data:

networks:
  retro5:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/24
